//! Reproduction tests auto-generated by the Aretta conductor.
//!
//! This module hosts reproduction tests auto-generated by the Aretta
//! conductor per the repro-test-format contract: each generated PR adds
//! exactly one test file here plus one `mod` line in `repros/mod.rs`.
//!
//! This canary is hand-written and permanently green. Its purpose is to
//! keep the module's run command non-vacuous — a `repros::` filter with
//! zero matching tests would pass as "running 0 tests; ok" — and to prove
//! the module wiring and the `TempDatabase` reopen machinery on every CI
//! run.

use crate::common::{ExecRows, TempDatabase};
use tempfile::TempDir;

/// Committed rows must survive a TRUNCATE checkpoint followed by a full
/// close + reopen of the database file (WAL durability).
#[test]
fn canary_repros_module_wired() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("canary.db");

    {
        let db = TempDatabase::new_with_existent(&path);
        let conn = db.connect_limbo();

        conn.execute("CREATE TABLE repro(id INTEGER PRIMARY KEY, v TEXT)")
            .unwrap();
        conn.execute("INSERT INTO repro VALUES (1, 'alpha'), (2, 'beta'), (3, 'gamma')")
            .unwrap();

        // Move all committed WAL frames into the main database file and truncate the WAL.
        conn.execute("PRAGMA wal_checkpoint(TRUNCATE)").unwrap();
        conn.close().unwrap();
    }

    {
        // Reopen the same database file; the committed rows must still be there.
        let db = TempDatabase::new_with_existent(&path);
        let conn = db.connect_limbo();

        let rows: Vec<(i64, String)> = conn.exec_rows("SELECT id, v FROM repro ORDER BY id");
        assert_eq!(
            rows,
            vec![(1, "alpha".into()), (2, "beta".into()), (3, "gamma".into())],
            "committed rows lost across checkpoint + reopen (WAL durability violation)"
        );
        conn.close().unwrap();
    }
}
